name: Build IPA for iCloud
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  mobile:
    uses: ./.github/workflows/release-mobile.yml
    with:
      version: 0.0.50
      ref: ${{ github.sha }}
